### PR TITLE
Removed deleted plugin newline.

### PR DESCRIPTION
**Pull request by Akronix**
Page https://plugins.geany.org/newline-plugin.html isn't listed in the sidebar anymore but the html page was still there.
Similar to #8

### CODE REVIEW

**Comment by Skif-off** [comment]
> isn't listed in the sidebar anymore

See list of third-party plugins: [index.php#L70](https://github.com/geany/plugins.geany.org/blob/master/index.php#L70)

P.S. [content/newline-plugin.html#L33](https://github.com/geany/plugins.geany.org/blob/master/content/newline-plugin.html#L33): it's  ```newline-2015-03.zip``` now, not ```newline-2014-03.zip```.

**Comment by Akronix** [comment]
Oh, true. I've never seen that plugin around and I thought it was too old.
Is it working for newer versions of Geany though? because in the webpage it says "geany 0.19" which is pretty old.

**Comment by Skif-off** [comment]
```newline.so```/````newline.dll``` from archive are not working, but I builded it with Geany 1.34 (from Github) and it works.

**Comment by Akronix** [comment]
OK, so I close this and open a new one for the right zip file.

**Pull request closed without merging**
