### PR TITLE
Update GPG key id for verifying downloads

### PR DESCRIPTION
**Pull request by eht16**

### CODE REVIEW

**Comment by msphn** [comment]
http://download.geany.org/frlan-pubkey-2018.txt

Doesn't exist according to my curl?

**Comment by eht16** [comment]
> http://download.geany.org/frlan-pubkey-2018.txt
> 
> Doesn't exist according to my curl?

The URL is correct. The file permissions were too restrict but fixed now
and you should get a 200.

**Comment by eht16** [comment]
And ideally, please squash the two commits before merging, thanks.

**Comment by msphn** [comment]
You are welcome.

**Pull request merged**
