### PR TITLE
Offer a Windows easy install by chocolatey

### PR DESCRIPTION
**Pull request by tunisiano187**
This change is [Reviewable](https://reviewable.io/reviews/geany/plugins.geany.org/21)

### CODE REVIEW

**Comment by msphn** [comment]
Why this tool? There are plenty of different package managers for windows. I would rather recommend to publish Geany to Microsoft's official ecosystem: https://github.com/microsoft/winget-cli

**Comment by tunisiano187** [comment]
Hi,
Just to have a windows version.
and i'm maintainer of many chocolatey packages.
the winget, i don't really know their work, but chocolatey is the conceptor of the idea in windows.
Winget seems to be newer and mostly copied of choco.
they both need installation, and chocolatey support nearly every windows.
winget requires Windows 10 1709 (build 16299) or later at this time

So you'll loose every others.

**Comment by tunisiano187** [comment]
No, i totally understand ;-) you don't even know me ;-) so it's logic ;-)
That's also the reason i've made research before

**Comment by msphn** [comment]
Thank you for your PR 👍

**Pull request merged**
